FROM nginx:latest

COPY hack/compose/nginx.conf /etc/nginx/nginx.conf
COPY dist /usr/share/nginx/html
COPY hack/compose/frontend-config.json /usr/share/nginx/html/config.json

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
