// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/orbit/dao/model"
)

func newJobCheckpoint(db *gorm.DB, opts ...gen.DOOption) jobCheckpoint {
	_jobCheckpoint := jobCheckpoint{}

	_jobCheckpoint.jobCheckpointDo.UseDB(db, opts...)
	_jobCheckpoint.jobCheckpointDo.UseModel(&model.JobCheckpoint{})

	tableName := _jobCheckpoint.jobCheckpointDo.TableName()
	_jobCheckpoint.ALL = field.NewAsterisk(tableName)
	_jobCheckpoint.ID = field.NewUint(tableName, "id")
	_jobCheckpoint.CreatedAt = field.NewTime(tableName, "created_at")
	_jobCheckpoint.UpdatedAt = field.NewTime(tableName, "updated_at")
	_jobCheckpoint.DeletedAt = field.NewField(tableName, "deleted_at")
	_jobCheckpoint.JobID = field.NewUint(tableName, "job_id")
	_jobCheckpoint.RunID = field.NewUint(tableName, "run_id")
	_jobCheckpoint.JobName = field.NewString(tableName, "job_name")
	_jobCheckpoint.UserID = field.NewUint(tableName, "user_id")
	_jobCheckpoint.AccountID = field.NewUint(tableName, "account_id")
	_jobCheckpoint.Framework = field.NewString(tableName, "framework")
	_jobCheckpoint.Name = field.NewString(tableName, "name")
	_jobCheckpoint.Path = field.NewString(tableName, "path")
	_jobCheckpoint.StoragePath = field.NewString(tableName, "storage_path")
	_jobCheckpoint.Step = field.NewInt64(tableName, "step")
	_jobCheckpoint.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_jobCheckpoint.ModTime = field.NewTime(tableName, "mod_time")
	_jobCheckpoint.Status = field.NewString(tableName, "status")
	_jobCheckpoint.Latest = field.NewBool(tableName, "latest")
	_jobCheckpoint.Source = field.NewString(tableName, "source")
	_jobCheckpoint.Metadata = field.NewField(tableName, "metadata")

	_jobCheckpoint.fillFieldMap()

	return _jobCheckpoint
}

type jobCheckpoint struct {
	jobCheckpointDo jobCheckpointDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	JobID       field.Uint   // 作业ID
	RunID       field.Uint   // 关联的实验 Run ID
	JobName     field.String // 作业集群名称
	UserID      field.Uint   // 用户ID
	AccountID   field.Uint   // 账户ID
	Framework   field.String // 训练框架
	Name        field.String // checkpoint名称
	Path        field.String // 容器内checkpoint路径
	StoragePath field.String // 存储根目录下的相对路径
	Step        field.Int64  // checkpoint步数，无法识别时为-1
	SizeBytes   field.Int64  // checkpoint大小
	ModTime     field.Time   // checkpoint最后修改时间
	Status      field.String // checkpoint状态
	Latest      field.Bool   // 是否为最新checkpoint
	Source      field.String // 来源(scan/manual)
	Metadata    field.Field  // checkpoint元数据

	fieldMap map[string]field.Expr
}

func (j jobCheckpoint) Table(newTableName string) *jobCheckpoint {
	j.jobCheckpointDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobCheckpoint) As(alias string) *jobCheckpoint {
	j.jobCheckpointDo.DO = *(j.jobCheckpointDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobCheckpoint) updateTableName(table string) *jobCheckpoint {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewUint(table, "id")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.DeletedAt = field.NewField(table, "deleted_at")
	j.JobID = field.NewUint(table, "job_id")
	j.RunID = field.NewUint(table, "run_id")
	j.JobName = field.NewString(table, "job_name")
	j.UserID = field.NewUint(table, "user_id")
	j.AccountID = field.NewUint(table, "account_id")
	j.Framework = field.NewString(table, "framework")
	j.Name = field.NewString(table, "name")
	j.Path = field.NewString(table, "path")
	j.StoragePath = field.NewString(table, "storage_path")
	j.Step = field.NewInt64(table, "step")
	j.SizeBytes = field.NewInt64(table, "size_bytes")
	j.ModTime = field.NewTime(table, "mod_time")
	j.Status = field.NewString(table, "status")
	j.Latest = field.NewBool(table, "latest")
	j.Source = field.NewString(table, "source")
	j.Metadata = field.NewField(table, "metadata")

	j.fillFieldMap()

	return j
}

func (j *jobCheckpoint) WithContext(ctx context.Context) IJobCheckpointDo {
	return j.jobCheckpointDo.WithContext(ctx)
}

func (j jobCheckpoint) TableName() string { return j.jobCheckpointDo.TableName() }

func (j jobCheckpoint) Alias() string { return j.jobCheckpointDo.Alias() }

func (j jobCheckpoint) Columns(cols ...field.Expr) gen.Columns {
	return j.jobCheckpointDo.Columns(cols...)
}

func (j *jobCheckpoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobCheckpoint) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 20)
	j.fieldMap["id"] = j.ID
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["deleted_at"] = j.DeletedAt
	j.fieldMap["job_id"] = j.JobID
	j.fieldMap["run_id"] = j.RunID
	j.fieldMap["job_name"] = j.JobName
	j.fieldMap["user_id"] = j.UserID
	j.fieldMap["account_id"] = j.AccountID
	j.fieldMap["framework"] = j.Framework
	j.fieldMap["name"] = j.Name
	j.fieldMap["path"] = j.Path
	j.fieldMap["storage_path"] = j.StoragePath
	j.fieldMap["step"] = j.Step
	j.fieldMap["size_bytes"] = j.SizeBytes
	j.fieldMap["mod_time"] = j.ModTime
	j.fieldMap["status"] = j.Status
	j.fieldMap["latest"] = j.Latest
	j.fieldMap["source"] = j.Source
	j.fieldMap["metadata"] = j.Metadata
}

func (j jobCheckpoint) clone(db *gorm.DB) jobCheckpoint {
	j.jobCheckpointDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobCheckpoint) replaceDB(db *gorm.DB) jobCheckpoint {
	j.jobCheckpointDo.ReplaceDB(db)
	return j
}

type jobCheckpointDo struct{ gen.DO }

type IJobCheckpointDo interface {
	gen.SubQuery
	Debug() IJobCheckpointDo
	WithContext(ctx context.Context) IJobCheckpointDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobCheckpointDo
	WriteDB() IJobCheckpointDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobCheckpointDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobCheckpointDo
	Not(conds ...gen.Condition) IJobCheckpointDo
	Or(conds ...gen.Condition) IJobCheckpointDo
	Select(conds ...field.Expr) IJobCheckpointDo
	Where(conds ...gen.Condition) IJobCheckpointDo
	Order(conds ...field.Expr) IJobCheckpointDo
	Distinct(cols ...field.Expr) IJobCheckpointDo
	Omit(cols ...field.Expr) IJobCheckpointDo
	Join(table schema.Tabler, on ...field.Expr) IJobCheckpointDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobCheckpointDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobCheckpointDo
	Group(cols ...field.Expr) IJobCheckpointDo
	Having(conds ...gen.Condition) IJobCheckpointDo
	Limit(limit int) IJobCheckpointDo
	Offset(offset int) IJobCheckpointDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobCheckpointDo
	Unscoped() IJobCheckpointDo
	Create(values ...*model.JobCheckpoint) error
	CreateInBatches(values []*model.JobCheckpoint, batchSize int) error
	Save(values ...*model.JobCheckpoint) error
	First() (*model.JobCheckpoint, error)
	Take() (*model.JobCheckpoint, error)
	Last() (*model.JobCheckpoint, error)
	Find() ([]*model.JobCheckpoint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobCheckpoint, err error)
	FindInBatches(result *[]*model.JobCheckpoint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.JobCheckpoint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobCheckpointDo
	Assign(attrs ...field.AssignExpr) IJobCheckpointDo
	Joins(fields ...field.RelationField) IJobCheckpointDo
	Preload(fields ...field.RelationField) IJobCheckpointDo
	FirstOrInit() (*model.JobCheckpoint, error)
	FirstOrCreate() (*model.JobCheckpoint, error)
	FindByPage(offset int, limit int) (result []*model.JobCheckpoint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobCheckpointDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobCheckpointDo) Debug() IJobCheckpointDo {
	return j.withDO(j.DO.Debug())
}

func (j jobCheckpointDo) WithContext(ctx context.Context) IJobCheckpointDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobCheckpointDo) ReadDB() IJobCheckpointDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobCheckpointDo) WriteDB() IJobCheckpointDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobCheckpointDo) Session(config *gorm.Session) IJobCheckpointDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobCheckpointDo) Clauses(conds ...clause.Expression) IJobCheckpointDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobCheckpointDo) Returning(value interface{}, columns ...string) IJobCheckpointDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobCheckpointDo) Not(conds ...gen.Condition) IJobCheckpointDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobCheckpointDo) Or(conds ...gen.Condition) IJobCheckpointDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobCheckpointDo) Select(conds ...field.Expr) IJobCheckpointDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobCheckpointDo) Where(conds ...gen.Condition) IJobCheckpointDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobCheckpointDo) Order(conds ...field.Expr) IJobCheckpointDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobCheckpointDo) Distinct(cols ...field.Expr) IJobCheckpointDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobCheckpointDo) Omit(cols ...field.Expr) IJobCheckpointDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobCheckpointDo) Join(table schema.Tabler, on ...field.Expr) IJobCheckpointDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobCheckpointDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobCheckpointDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobCheckpointDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobCheckpointDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobCheckpointDo) Group(cols ...field.Expr) IJobCheckpointDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobCheckpointDo) Having(conds ...gen.Condition) IJobCheckpointDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobCheckpointDo) Limit(limit int) IJobCheckpointDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobCheckpointDo) Offset(offset int) IJobCheckpointDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobCheckpointDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobCheckpointDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobCheckpointDo) Unscoped() IJobCheckpointDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobCheckpointDo) Create(values ...*model.JobCheckpoint) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobCheckpointDo) CreateInBatches(values []*model.JobCheckpoint, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobCheckpointDo) Save(values ...*model.JobCheckpoint) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobCheckpointDo) First() (*model.JobCheckpoint, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCheckpoint), nil
	}
}

func (j jobCheckpointDo) Take() (*model.JobCheckpoint, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCheckpoint), nil
	}
}

func (j jobCheckpointDo) Last() (*model.JobCheckpoint, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCheckpoint), nil
	}
}

func (j jobCheckpointDo) Find() ([]*model.JobCheckpoint, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobCheckpoint), err
}

func (j jobCheckpointDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobCheckpoint, err error) {
	buf := make([]*model.JobCheckpoint, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobCheckpointDo) FindInBatches(result *[]*model.JobCheckpoint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobCheckpointDo) Attrs(attrs ...field.AssignExpr) IJobCheckpointDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobCheckpointDo) Assign(attrs ...field.AssignExpr) IJobCheckpointDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobCheckpointDo) Joins(fields ...field.RelationField) IJobCheckpointDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobCheckpointDo) Preload(fields ...field.RelationField) IJobCheckpointDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobCheckpointDo) FirstOrInit() (*model.JobCheckpoint, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCheckpoint), nil
	}
}

func (j jobCheckpointDo) FirstOrCreate() (*model.JobCheckpoint, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobCheckpoint), nil
	}
}

func (j jobCheckpointDo) FindByPage(offset int, limit int) (result []*model.JobCheckpoint, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobCheckpointDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobCheckpointDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobCheckpointDo) Delete(models ...*model.JobCheckpoint) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobCheckpointDo) withDO(do gen.Dao) *jobCheckpointDo {
	j.DO = *do.(*gen.DO)
	return j
}
