// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/orbit/dao/model"
)

func newRunArtifact(db *gorm.DB, opts ...gen.DOOption) runArtifact {
	_runArtifact := runArtifact{}

	_runArtifact.runArtifactDo.UseDB(db, opts...)
	_runArtifact.runArtifactDo.UseModel(&model.RunArtifact{})

	tableName := _runArtifact.runArtifactDo.TableName()
	_runArtifact.ALL = field.NewAsterisk(tableName)
	_runArtifact.ID = field.NewUint(tableName, "id")
	_runArtifact.CreatedAt = field.NewTime(tableName, "created_at")
	_runArtifact.UpdatedAt = field.NewTime(tableName, "updated_at")
	_runArtifact.DeletedAt = field.NewField(tableName, "deleted_at")
	_runArtifact.RunID = field.NewUint(tableName, "run_id")
	_runArtifact.ClientRecordID = field.NewString(tableName, "client_record_id")
	_runArtifact.Name = field.NewString(tableName, "name")
	_runArtifact.Type = field.NewString(tableName, "type")
	_runArtifact.Path = field.NewString(tableName, "path")
	_runArtifact.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_runArtifact.SourceType = field.NewString(tableName, "source_type")
	_runArtifact.SourceID = field.NewUint(tableName, "source_id")
	_runArtifact.Metadata = field.NewField(tableName, "metadata")
	_runArtifact.Run = runArtifactBelongsToRun{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Run", "model.ExperimentRun"),
		Experiment: struct {
			field.RelationField
			User struct {
				field.RelationField
				UserAccounts struct {
					field.RelationField
				}
				UserDatasets struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				UserAccounts struct {
					field.RelationField
				}
				AccountDatasets struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Run.Experiment", "model.Experiment"),
			User: struct {
				field.RelationField
				UserAccounts struct {
					field.RelationField
				}
				UserDatasets struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Run.Experiment.User", "model.User"),
				UserAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Run.Experiment.User.UserAccounts", "model.UserAccount"),
				},
				UserDatasets: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Run.Experiment.User.UserDatasets", "model.UserDataset"),
				},
			},
			Account: struct {
				field.RelationField
				UserAccounts struct {
					field.RelationField
				}
				AccountDatasets struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Run.Experiment.Account", "model.Account"),
				UserAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Run.Experiment.Account.UserAccounts", "model.UserAccount"),
				},
				AccountDatasets: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Run.Experiment.Account.AccountDatasets", "model.AccountDataset"),
				},
			},
		},
	}

	_runArtifact.fillFieldMap()

	return _runArtifact
}

type runArtifact struct {
	runArtifactDo runArtifactDo

	ALL            field.Asterisk
	ID             field.Uint
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field
	RunID          field.Uint
	ClientRecordID field.String // SDK离线记录ID
	Name           field.String
	Type           field.String
	Path           field.String
	SizeBytes      field.Int64
	SourceType     field.String // 来源类型
	SourceID       field.Uint   // 来源记录ID
	Metadata       field.Field
	Run            runArtifactBelongsToRun

	fieldMap map[string]field.Expr
}

func (r runArtifact) Table(newTableName string) *runArtifact {
	r.runArtifactDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runArtifact) As(alias string) *runArtifact {
	r.runArtifactDo.DO = *(r.runArtifactDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runArtifact) updateTableName(table string) *runArtifact {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.RunID = field.NewUint(table, "run_id")
	r.ClientRecordID = field.NewString(table, "client_record_id")
	r.Name = field.NewString(table, "name")
	r.Type = field.NewString(table, "type")
	r.Path = field.NewString(table, "path")
	r.SizeBytes = field.NewInt64(table, "size_bytes")
	r.SourceType = field.NewString(table, "source_type")
	r.SourceID = field.NewUint(table, "source_id")
	r.Metadata = field.NewField(table, "metadata")

	r.fillFieldMap()

	return r
}

func (r *runArtifact) WithContext(ctx context.Context) IRunArtifactDo {
	return r.runArtifactDo.WithContext(ctx)
}

func (r runArtifact) TableName() string { return r.runArtifactDo.TableName() }

func (r runArtifact) Alias() string { return r.runArtifactDo.Alias() }

func (r runArtifact) Columns(cols ...field.Expr) gen.Columns { return r.runArtifactDo.Columns(cols...) }

func (r *runArtifact) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runArtifact) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 14)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["run_id"] = r.RunID
	r.fieldMap["client_record_id"] = r.ClientRecordID
	r.fieldMap["name"] = r.Name
	r.fieldMap["type"] = r.Type
	r.fieldMap["path"] = r.Path
	r.fieldMap["size_bytes"] = r.SizeBytes
	r.fieldMap["source_type"] = r.SourceType
	r.fieldMap["source_id"] = r.SourceID
	r.fieldMap["metadata"] = r.Metadata

}

func (r runArtifact) clone(db *gorm.DB) runArtifact {
	r.runArtifactDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Run.db = db.Session(&gorm.Session{Initialized: true})
	r.Run.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r runArtifact) replaceDB(db *gorm.DB) runArtifact {
	r.runArtifactDo.ReplaceDB(db)
	r.Run.db = db.Session(&gorm.Session{})
	return r
}

type runArtifactBelongsToRun struct {
	db *gorm.DB

	field.RelationField

	Experiment struct {
		field.RelationField
		User struct {
			field.RelationField
			UserAccounts struct {
				field.RelationField
			}
			UserDatasets struct {
				field.RelationField
			}
		}
		Account struct {
			field.RelationField
			UserAccounts struct {
				field.RelationField
			}
			AccountDatasets struct {
				field.RelationField
			}
		}
	}
}

func (a runArtifactBelongsToRun) Where(conds ...field.Expr) *runArtifactBelongsToRun {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a runArtifactBelongsToRun) WithContext(ctx context.Context) *runArtifactBelongsToRun {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a runArtifactBelongsToRun) Session(session *gorm.Session) *runArtifactBelongsToRun {
	a.db = a.db.Session(session)
	return &a
}

func (a runArtifactBelongsToRun) Model(m *model.RunArtifact) *runArtifactBelongsToRunTx {
	return &runArtifactBelongsToRunTx{a.db.Model(m).Association(a.Name())}
}

func (a runArtifactBelongsToRun) Unscoped() *runArtifactBelongsToRun {
	a.db = a.db.Unscoped()
	return &a
}

type runArtifactBelongsToRunTx struct{ tx *gorm.Association }

func (a runArtifactBelongsToRunTx) Find() (result *model.ExperimentRun, err error) {
	return result, a.tx.Find(&result)
}

func (a runArtifactBelongsToRunTx) Append(values ...*model.ExperimentRun) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a runArtifactBelongsToRunTx) Replace(values ...*model.ExperimentRun) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a runArtifactBelongsToRunTx) Delete(values ...*model.ExperimentRun) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a runArtifactBelongsToRunTx) Clear() error {
	return a.tx.Clear()
}

func (a runArtifactBelongsToRunTx) Count() int64 {
	return a.tx.Count()
}

func (a runArtifactBelongsToRunTx) Unscoped() *runArtifactBelongsToRunTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type runArtifactDo struct{ gen.DO }

type IRunArtifactDo interface {
	gen.SubQuery
	Debug() IRunArtifactDo
	WithContext(ctx context.Context) IRunArtifactDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRunArtifactDo
	WriteDB() IRunArtifactDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRunArtifactDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRunArtifactDo
	Not(conds ...gen.Condition) IRunArtifactDo
	Or(conds ...gen.Condition) IRunArtifactDo
	Select(conds ...field.Expr) IRunArtifactDo
	Where(conds ...gen.Condition) IRunArtifactDo
	Order(conds ...field.Expr) IRunArtifactDo
	Distinct(cols ...field.Expr) IRunArtifactDo
	Omit(cols ...field.Expr) IRunArtifactDo
	Join(table schema.Tabler, on ...field.Expr) IRunArtifactDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRunArtifactDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRunArtifactDo
	Group(cols ...field.Expr) IRunArtifactDo
	Having(conds ...gen.Condition) IRunArtifactDo
	Limit(limit int) IRunArtifactDo
	Offset(offset int) IRunArtifactDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRunArtifactDo
	Unscoped() IRunArtifactDo
	Create(values ...*model.RunArtifact) error
	CreateInBatches(values []*model.RunArtifact, batchSize int) error
	Save(values ...*model.RunArtifact) error
	First() (*model.RunArtifact, error)
	Take() (*model.RunArtifact, error)
	Last() (*model.RunArtifact, error)
	Find() ([]*model.RunArtifact, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunArtifact, err error)
	FindInBatches(result *[]*model.RunArtifact, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RunArtifact) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRunArtifactDo
	Assign(attrs ...field.AssignExpr) IRunArtifactDo
	Joins(fields ...field.RelationField) IRunArtifactDo
	Preload(fields ...field.RelationField) IRunArtifactDo
	FirstOrInit() (*model.RunArtifact, error)
	FirstOrCreate() (*model.RunArtifact, error)
	FindByPage(offset int, limit int) (result []*model.RunArtifact, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRunArtifactDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r runArtifactDo) Debug() IRunArtifactDo {
	return r.withDO(r.DO.Debug())
}

func (r runArtifactDo) WithContext(ctx context.Context) IRunArtifactDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r runArtifactDo) ReadDB() IRunArtifactDo {
	return r.Clauses(dbresolver.Read)
}

func (r runArtifactDo) WriteDB() IRunArtifactDo {
	return r.Clauses(dbresolver.Write)
}

func (r runArtifactDo) Session(config *gorm.Session) IRunArtifactDo {
	return r.withDO(r.DO.Session(config))
}

func (r runArtifactDo) Clauses(conds ...clause.Expression) IRunArtifactDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r runArtifactDo) Returning(value interface{}, columns ...string) IRunArtifactDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r runArtifactDo) Not(conds ...gen.Condition) IRunArtifactDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r runArtifactDo) Or(conds ...gen.Condition) IRunArtifactDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r runArtifactDo) Select(conds ...field.Expr) IRunArtifactDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r runArtifactDo) Where(conds ...gen.Condition) IRunArtifactDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r runArtifactDo) Order(conds ...field.Expr) IRunArtifactDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r runArtifactDo) Distinct(cols ...field.Expr) IRunArtifactDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r runArtifactDo) Omit(cols ...field.Expr) IRunArtifactDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r runArtifactDo) Join(table schema.Tabler, on ...field.Expr) IRunArtifactDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r runArtifactDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRunArtifactDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r runArtifactDo) RightJoin(table schema.Tabler, on ...field.Expr) IRunArtifactDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r runArtifactDo) Group(cols ...field.Expr) IRunArtifactDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r runArtifactDo) Having(conds ...gen.Condition) IRunArtifactDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r runArtifactDo) Limit(limit int) IRunArtifactDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r runArtifactDo) Offset(offset int) IRunArtifactDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r runArtifactDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRunArtifactDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r runArtifactDo) Unscoped() IRunArtifactDo {
	return r.withDO(r.DO.Unscoped())
}

func (r runArtifactDo) Create(values ...*model.RunArtifact) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r runArtifactDo) CreateInBatches(values []*model.RunArtifact, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r runArtifactDo) Save(values ...*model.RunArtifact) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r runArtifactDo) First() (*model.RunArtifact, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunArtifact), nil
	}
}

func (r runArtifactDo) Take() (*model.RunArtifact, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunArtifact), nil
	}
}

func (r runArtifactDo) Last() (*model.RunArtifact, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunArtifact), nil
	}
}

func (r runArtifactDo) Find() ([]*model.RunArtifact, error) {
	result, err := r.DO.Find()
	return result.([]*model.RunArtifact), err
}

func (r runArtifactDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunArtifact, err error) {
	buf := make([]*model.RunArtifact, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r runArtifactDo) FindInBatches(result *[]*model.RunArtifact, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r runArtifactDo) Attrs(attrs ...field.AssignExpr) IRunArtifactDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r runArtifactDo) Assign(attrs ...field.AssignExpr) IRunArtifactDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r runArtifactDo) Joins(fields ...field.RelationField) IRunArtifactDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r runArtifactDo) Preload(fields ...field.RelationField) IRunArtifactDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r runArtifactDo) FirstOrInit() (*model.RunArtifact, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunArtifact), nil
	}
}

func (r runArtifactDo) FirstOrCreate() (*model.RunArtifact, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunArtifact), nil
	}
}

func (r runArtifactDo) FindByPage(offset int, limit int) (result []*model.RunArtifact, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r runArtifactDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r runArtifactDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r runArtifactDo) Delete(models ...*model.RunArtifact) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *runArtifactDo) withDO(do gen.Dao) *runArtifactDo {
	r.DO = *do.(*gen.DO)
	return r
}
