// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/orbit/dao/model"
)

func newRunMetric(db *gorm.DB, opts ...gen.DOOption) runMetric {
	_runMetric := runMetric{}

	_runMetric.runMetricDo.UseDB(db, opts...)
	_runMetric.runMetricDo.UseModel(&model.RunMetric{})

	tableName := _runMetric.runMetricDo.TableName()
	_runMetric.ALL = field.NewAsterisk(tableName)
	_runMetric.ID = field.NewUint(tableName, "id")
	_runMetric.CreatedAt = field.NewTime(tableName, "created_at")
	_runMetric.UpdatedAt = field.NewTime(tableName, "updated_at")
	_runMetric.DeletedAt = field.NewField(tableName, "deleted_at")
	_runMetric.RunID = field.NewUint(tableName, "run_id")
	_runMetric.ClientRecordID = field.NewString(tableName, "client_record_id")
	_runMetric.Name = field.NewString(tableName, "name")
	_runMetric.Step = field.NewInt64(tableName, "step")
	_runMetric.Value = field.NewFloat64(tableName, "value")
	_runMetric.Timestamp = field.NewTime(tableName, "timestamp")
	_runMetric.Context = field.NewField(tableName, "context")
	_runMetric.Run = runMetricBelongsToRun{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Run", "model.ExperimentRun"),
		Experiment: struct {
			field.RelationField
			User struct {
				field.RelationField
				UserAccounts struct {
					field.RelationField
				}
				UserDatasets struct {
					field.RelationField
				}
			}
			Account struct {
				field.RelationField
				UserAccounts struct {
					field.RelationField
				}
				AccountDatasets struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Run.Experiment", "model.Experiment"),
			User: struct {
				field.RelationField
				UserAccounts struct {
					field.RelationField
				}
				UserDatasets struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Run.Experiment.User", "model.User"),
				UserAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Run.Experiment.User.UserAccounts", "model.UserAccount"),
				},
				UserDatasets: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Run.Experiment.User.UserDatasets", "model.UserDataset"),
				},
			},
			Account: struct {
				field.RelationField
				UserAccounts struct {
					field.RelationField
				}
				AccountDatasets struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Run.Experiment.Account", "model.Account"),
				UserAccounts: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Run.Experiment.Account.UserAccounts", "model.UserAccount"),
				},
				AccountDatasets: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Run.Experiment.Account.AccountDatasets", "model.AccountDataset"),
				},
			},
		},
	}

	_runMetric.fillFieldMap()

	return _runMetric
}

type runMetric struct {
	runMetricDo runMetricDo

	ALL            field.Asterisk
	ID             field.Uint
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field
	RunID          field.Uint
	ClientRecordID field.String // SDK离线记录ID
	Name           field.String
	Step           field.Int64
	Value          field.Float64
	Timestamp      field.Time
	Context        field.Field
	Run            runMetricBelongsToRun

	fieldMap map[string]field.Expr
}

func (r runMetric) Table(newTableName string) *runMetric {
	r.runMetricDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r runMetric) As(alias string) *runMetric {
	r.runMetricDo.DO = *(r.runMetricDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *runMetric) updateTableName(table string) *runMetric {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.RunID = field.NewUint(table, "run_id")
	r.ClientRecordID = field.NewString(table, "client_record_id")
	r.Name = field.NewString(table, "name")
	r.Step = field.NewInt64(table, "step")
	r.Value = field.NewFloat64(table, "value")
	r.Timestamp = field.NewTime(table, "timestamp")
	r.Context = field.NewField(table, "context")

	r.fillFieldMap()

	return r
}

func (r *runMetric) WithContext(ctx context.Context) IRunMetricDo {
	return r.runMetricDo.WithContext(ctx)
}

func (r runMetric) TableName() string { return r.runMetricDo.TableName() }

func (r runMetric) Alias() string { return r.runMetricDo.Alias() }

func (r runMetric) Columns(cols ...field.Expr) gen.Columns { return r.runMetricDo.Columns(cols...) }

func (r *runMetric) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *runMetric) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["run_id"] = r.RunID
	r.fieldMap["client_record_id"] = r.ClientRecordID
	r.fieldMap["name"] = r.Name
	r.fieldMap["step"] = r.Step
	r.fieldMap["value"] = r.Value
	r.fieldMap["timestamp"] = r.Timestamp
	r.fieldMap["context"] = r.Context

}

func (r runMetric) clone(db *gorm.DB) runMetric {
	r.runMetricDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Run.db = db.Session(&gorm.Session{Initialized: true})
	r.Run.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r runMetric) replaceDB(db *gorm.DB) runMetric {
	r.runMetricDo.ReplaceDB(db)
	r.Run.db = db.Session(&gorm.Session{})
	return r
}

type runMetricBelongsToRun struct {
	db *gorm.DB

	field.RelationField

	Experiment struct {
		field.RelationField
		User struct {
			field.RelationField
			UserAccounts struct {
				field.RelationField
			}
			UserDatasets struct {
				field.RelationField
			}
		}
		Account struct {
			field.RelationField
			UserAccounts struct {
				field.RelationField
			}
			AccountDatasets struct {
				field.RelationField
			}
		}
	}
}

func (a runMetricBelongsToRun) Where(conds ...field.Expr) *runMetricBelongsToRun {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a runMetricBelongsToRun) WithContext(ctx context.Context) *runMetricBelongsToRun {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a runMetricBelongsToRun) Session(session *gorm.Session) *runMetricBelongsToRun {
	a.db = a.db.Session(session)
	return &a
}

func (a runMetricBelongsToRun) Model(m *model.RunMetric) *runMetricBelongsToRunTx {
	return &runMetricBelongsToRunTx{a.db.Model(m).Association(a.Name())}
}

func (a runMetricBelongsToRun) Unscoped() *runMetricBelongsToRun {
	a.db = a.db.Unscoped()
	return &a
}

type runMetricBelongsToRunTx struct{ tx *gorm.Association }

func (a runMetricBelongsToRunTx) Find() (result *model.ExperimentRun, err error) {
	return result, a.tx.Find(&result)
}

func (a runMetricBelongsToRunTx) Append(values ...*model.ExperimentRun) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a runMetricBelongsToRunTx) Replace(values ...*model.ExperimentRun) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a runMetricBelongsToRunTx) Delete(values ...*model.ExperimentRun) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a runMetricBelongsToRunTx) Clear() error {
	return a.tx.Clear()
}

func (a runMetricBelongsToRunTx) Count() int64 {
	return a.tx.Count()
}

func (a runMetricBelongsToRunTx) Unscoped() *runMetricBelongsToRunTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type runMetricDo struct{ gen.DO }

type IRunMetricDo interface {
	gen.SubQuery
	Debug() IRunMetricDo
	WithContext(ctx context.Context) IRunMetricDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRunMetricDo
	WriteDB() IRunMetricDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRunMetricDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRunMetricDo
	Not(conds ...gen.Condition) IRunMetricDo
	Or(conds ...gen.Condition) IRunMetricDo
	Select(conds ...field.Expr) IRunMetricDo
	Where(conds ...gen.Condition) IRunMetricDo
	Order(conds ...field.Expr) IRunMetricDo
	Distinct(cols ...field.Expr) IRunMetricDo
	Omit(cols ...field.Expr) IRunMetricDo
	Join(table schema.Tabler, on ...field.Expr) IRunMetricDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRunMetricDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRunMetricDo
	Group(cols ...field.Expr) IRunMetricDo
	Having(conds ...gen.Condition) IRunMetricDo
	Limit(limit int) IRunMetricDo
	Offset(offset int) IRunMetricDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRunMetricDo
	Unscoped() IRunMetricDo
	Create(values ...*model.RunMetric) error
	CreateInBatches(values []*model.RunMetric, batchSize int) error
	Save(values ...*model.RunMetric) error
	First() (*model.RunMetric, error)
	Take() (*model.RunMetric, error)
	Last() (*model.RunMetric, error)
	Find() ([]*model.RunMetric, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunMetric, err error)
	FindInBatches(result *[]*model.RunMetric, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RunMetric) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRunMetricDo
	Assign(attrs ...field.AssignExpr) IRunMetricDo
	Joins(fields ...field.RelationField) IRunMetricDo
	Preload(fields ...field.RelationField) IRunMetricDo
	FirstOrInit() (*model.RunMetric, error)
	FirstOrCreate() (*model.RunMetric, error)
	FindByPage(offset int, limit int) (result []*model.RunMetric, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRunMetricDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r runMetricDo) Debug() IRunMetricDo {
	return r.withDO(r.DO.Debug())
}

func (r runMetricDo) WithContext(ctx context.Context) IRunMetricDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r runMetricDo) ReadDB() IRunMetricDo {
	return r.Clauses(dbresolver.Read)
}

func (r runMetricDo) WriteDB() IRunMetricDo {
	return r.Clauses(dbresolver.Write)
}

func (r runMetricDo) Session(config *gorm.Session) IRunMetricDo {
	return r.withDO(r.DO.Session(config))
}

func (r runMetricDo) Clauses(conds ...clause.Expression) IRunMetricDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r runMetricDo) Returning(value interface{}, columns ...string) IRunMetricDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r runMetricDo) Not(conds ...gen.Condition) IRunMetricDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r runMetricDo) Or(conds ...gen.Condition) IRunMetricDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r runMetricDo) Select(conds ...field.Expr) IRunMetricDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r runMetricDo) Where(conds ...gen.Condition) IRunMetricDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r runMetricDo) Order(conds ...field.Expr) IRunMetricDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r runMetricDo) Distinct(cols ...field.Expr) IRunMetricDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r runMetricDo) Omit(cols ...field.Expr) IRunMetricDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r runMetricDo) Join(table schema.Tabler, on ...field.Expr) IRunMetricDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r runMetricDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRunMetricDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r runMetricDo) RightJoin(table schema.Tabler, on ...field.Expr) IRunMetricDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r runMetricDo) Group(cols ...field.Expr) IRunMetricDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r runMetricDo) Having(conds ...gen.Condition) IRunMetricDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r runMetricDo) Limit(limit int) IRunMetricDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r runMetricDo) Offset(offset int) IRunMetricDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r runMetricDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRunMetricDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r runMetricDo) Unscoped() IRunMetricDo {
	return r.withDO(r.DO.Unscoped())
}

func (r runMetricDo) Create(values ...*model.RunMetric) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r runMetricDo) CreateInBatches(values []*model.RunMetric, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r runMetricDo) Save(values ...*model.RunMetric) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r runMetricDo) First() (*model.RunMetric, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunMetric), nil
	}
}

func (r runMetricDo) Take() (*model.RunMetric, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunMetric), nil
	}
}

func (r runMetricDo) Last() (*model.RunMetric, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunMetric), nil
	}
}

func (r runMetricDo) Find() ([]*model.RunMetric, error) {
	result, err := r.DO.Find()
	return result.([]*model.RunMetric), err
}

func (r runMetricDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RunMetric, err error) {
	buf := make([]*model.RunMetric, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r runMetricDo) FindInBatches(result *[]*model.RunMetric, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r runMetricDo) Attrs(attrs ...field.AssignExpr) IRunMetricDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r runMetricDo) Assign(attrs ...field.AssignExpr) IRunMetricDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r runMetricDo) Joins(fields ...field.RelationField) IRunMetricDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r runMetricDo) Preload(fields ...field.RelationField) IRunMetricDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r runMetricDo) FirstOrInit() (*model.RunMetric, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunMetric), nil
	}
}

func (r runMetricDo) FirstOrCreate() (*model.RunMetric, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RunMetric), nil
	}
}

func (r runMetricDo) FindByPage(offset int, limit int) (result []*model.RunMetric, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r runMetricDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r runMetricDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r runMetricDo) Delete(models ...*model.RunMetric) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *runMetricDo) withDO(do gen.Dao) *runMetricDo {
	r.DO = *do.(*gen.DO)
	return r
}
