apiVersion: v1
kind: Secret
metadata:
  name: orbit-web-backend-secret
  namespace: orbit
  annotations:
    kubernetes.io/service-account.name: orbit-web-backend
type: kubernetes.io/service-account-token
