{
 "title": "Orbit GPU 资源监控概览",
 "tags": [
  "A100",
  "A800",
  "H100",
  "智算中心",
  "NVIDIA",
  "GPU",
  "kason"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "idc", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(DCGM_FI_DEV_DEC_UTIL,Hostname)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL,namespace)"
    }
   },
   {
    "name": "model",
    "label": "Model",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL,modelName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU 资源监控概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU 卡申请与使用情况",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"})",
     "legendFormat": "总 GPU 卡"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"})",
     "legendFormat": "已申请 GPU 卡"
    },
    {
     "expr": "count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"}[1m])>0)",
     "legendFormat": "已使用 GPU 卡"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"})-count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"}[1m])>0)",
     "legendFormat": "未使用 GPU 卡"
    }
   ]
  },
  {
   "title": "GPU 型号分布",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (modelName) (DCGM_FI_DEV_DEC_UTIL{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 平均温度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 使用总功率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "已申请 GPU 利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"}[3m])>0) / count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"}) * avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "已使用 GPU 利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 分配情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"})",
     "legendFormat": "总数"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"}) or vector(0)",
     "legendFormat": "申请数"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"} > 0) or vector(0)",
     "legendFormat": "使用数"
    }
   ]
  },
  {
   "title": "GPU 总体利用率",
   "type": "timeseries",
   "description": "单台、多台汇总展示",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"}) / count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"})",
     "legendFormat": "GPU 使用率"
    }
   ]
  },
  {
   "title": "已申请 GPU 明细（节点维度）",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} * on (pod) group_left(host_ip) kube_pod_info) by (Hostname,host_ip,modelName)",
     "legendFormat": "总 GPU 资源"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\"}) by (Hostname)\nor\n(sum by (Hostname) (0 * count(DCGM_FI_DEV_GPU_UTIL) by (Hostname)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"}[1m])>0) by (Hostname)",
     "legendFormat": "已使用 GPU 资源"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} * on (pod) group_left(host_ip) kube_pod_info) by (Hostname) - (count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"}) by (Hostname)\nor\n(sum by (Hostname) (0 * count(DCGM_FI_DEV_GPU_UTIL) by (Hostname))))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU 使用明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "GPU 使用率明细（Job 粒度）",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg by (owner_name,modelName) (\n  label_replace(\n    DCGM_FI_DEV_GPU_UTIL{pod!=\"\", namespace=\"orbit-workspace\"},\n    \"pod\", \"$1\", \"pod\", \"(.*)\"\n  )\n  * on (pod) group_left(owner_name) kube_pod_owner{namespace=\"orbit-workspace\", owner_is_controller=\"true\", owner_kind=\"Job\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (owner_name) (\n  (\n    label_replace(\n      DCGM_FI_DEV_FB_USED{pod!=\"\", namespace=\"orbit-workspace\"},\n      \"pod\", \"$1\", \"pod\", \"(.*)\"\n    )\n    /\n    (\n      label_replace(\n        DCGM_FI_DEV_FB_USED{pod!=\"\", namespace=\"orbit-workspace\"},\n        \"pod\", \"$1\", \"pod\", \"(.*)\"\n      )\n      +\n      label_replace(\n        DCGM_FI_DEV_FB_FREE{pod!=\"\", namespace=\"orbit-workspace\"},\n        \"pod\", \"$1\", \"pod\", \"(.*)\"\n      )\n    )\n  ) * 100\n  * on (pod) group_left(owner_name) kube_pod_owner{namespace=\"orbit-workspace\", owner_is_controller=\"true\", owner_kind=\"Job\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (owner_name) (label_replace(\r\n    DCGM_FI_DEV_GPU_UTIL{pod!=\"\", namespace=\"orbit-workspace\"},\r\n    \"pod\", \"$1\", \"pod\", \"(.*)\"\r\n  )\r\n  * on (pod) group_left(owner_name) kube_pod_owner{namespace=\"orbit-workspace\", owner_is_controller=\"true\", owner_kind=\"Job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 使用率明细（Pod 粒度）",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"} * on (pod) group_left(host_ip) kube_pod_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "(DCGM_FI_DEV_FB_USED{pod!=\"\",Hostname=~\"$hostname\",namespace!=\"nvidia-gpu-operator\"}/(DCGM_FI_DEV_FB_USED{pod!=\"\",Hostname=~\"$hostname\",namespace!=\"nvidia-gpu-operator\"}+DCGM_FI_DEV_FB_FREE{pod!=\"\",Hostname=~\"$hostname\",namespace!=\"nvidia-gpu-operator\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 算力卡健康状态&版本信息概览",
   "type": "table",
   "description": "监控展示 NVIDIA 驱动版本、芯片类型、GPU 卡健康状态等",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"}) by (Hostname)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (Hostname,modelName,host_ip,DCGM_FI_DRIVER_VERSION) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(kube_node_info{node=~\"$hostname\"},\"Hostname\",\"$1\",\"node\",\"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by (node) (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"$hostname\"}[2m]))  / sum by (node) (kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$hostname\"}),\"Hostname\",\"$1\",\"node\",\"(.*)\")",
     "legendFormat": "CPU 使用率"
    },
    {
     "expr": "label_replace(sum by (node) (container_memory_working_set_bytes{container!=\"\",node=~\"$hostname\"}) / sum by (node) (kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$hostname\"}),\"Hostname\",\"$1\",\"node\",\"(.*)\")",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "avg by (Hostname) (DCGM_FI_DEV_MEM_CLOCK{Hostname=~\"$hostname\"}*1000000)",
     "legendFormat": "内存时钟频率"
    },
    {
     "expr": "avg by (Hostname) (DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$hostname\"}*1000000)",
     "legendFormat": "SM 时钟频率"
    }
   ]
  },
  {
   "title": "GPU 利用率（节点维度）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (Hostname,host_ip) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) ",
     "legendFormat": "{{Hostname}}"
    }
   ]
  },
  {
   "title": "GPU 显存使用率（单台展示）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(DCGM_FI_DEV_FB_USED{pod!=\"\",Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) by (Hostname,host_ip))/(sum(DCGM_FI_DEV_FB_USED{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) by (Hostname,host_ip)+sum(DCGM_FI_DEV_FB_FREE{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) by (Hostname,host_ip)) * 100",
     "legendFormat": "{{Hostname}}"
    }
   ]
  },
  { "title": "各型号 GPU 分配情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "$model 分配情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "repeat": "model",
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{modelName=\"$model\",Hostname=~\"$hostname\"})",
     "legendFormat": "总数"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{modelName=\"$model\",namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"}) or vector(0)",
     "legendFormat": "申请数"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{modelName=\"$model\",namespace!=\"nvidia-gpu-operator\",Hostname=~\"$hostname\"} > 0) or vector(0)",
     "legendFormat": "使用数"
    }
   ]
  }
 ]
}