{
 "title": "Orbit Pod Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node_name", "query": { "query": "label_values(node)" } },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(kube_pod_info{node=\"$node_name\"}, pod)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL{exported_pod=\"$pod_name\"},gpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running on",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=\"$pod_name\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Created by",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=\"$pod_name\"}",
     "legendFormat": "{{ created_by_kind }}: {{ created_by_name }}"
    }
   ]
  },
  { "title": "Basic monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{pod=\"$pod_name\",container!=\"POD\",container!=\"\"}[4m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=\"$pod_name\",container!=\"POD\",container!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod 网络接收流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(container_network_receive_bytes_total{pod=\"$pod_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod 网络发送流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{pod=\"$pod_name\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "GPU 利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "repeat": "gpu",
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}